### ISSUE TITLE
Error in processOptions.js as of version 0.2.4 with certain options.

### ISSUE THREAD

**Issue by threehams** [mixtur/webpack-spritesmith#16]
With the release of 0.2.4, I'm getting an error when attempting to build sprites. Everything works nicely when locking the version to 0.2.3.

Unfortunately, I set this up a month ago, and can't remember why I chose what I did - otherwise I'd try to track down what's happening.

Callstack:

```
TypeError: Cannot use 'in' operator to search for 'format' in undefined
    at normalizeOne (...\webpack-spritesmith\lib\processOptions.js:72:38)
    at Array.map (native)
    at normalizeTargetCss (...\webpack-spritesmith\lib\processOptions.js:60:36)
    at module.exports (...\webpack-spritesmith\lib\processOptions.js:28:5)
    at Object.SpritesmithPlugin (...\webpack-spritesmith\lib\Plugin.js:8:20)
    at Object.<anonymous> (webpack.config.js:25:5)
    at Module._compile (module.js:541:32)
    at loader (...\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (...\babel-register\lib\node.js:168:7)
    at Module.load (module.js:458:32)
```

Webpack configuration (development):

```
new SpritesmithPlugin({
  src: {
    cwd: './assets/icons',
    glob: '*.png'
  },
  target: {
    image: 'assets/icons.png',
    css: 'assets/icons.css'
  },
  apiOptions: {
    cssImageRef: './icons.png'
  },
}),
```

Environment:

Node 6.2.1
Windows 10
Webpack 1.12.15

**Comment by mixtur** [comment]
Uhh... sorry about that. Just fixed it.
