### ISSUE TITLE
syntax error in processOptions.js

### ISSUE THREAD

**Issue by shaurabh-singh** [mixtur/webpack-spritesmith#18]
Hi, 
In version 0.2.5, I'm facing this error at the time of compilation.  

`/usr/local/apache2/htdocs/xyz/current/node_modules/webpack-spritesmith/lib/processOptions.js:38
    _.forEach(mergedOptions.customTemplates, (template, templateName) => {
                                                                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/apache2/htdocs/xyz/current/node_modules/webpack-spritesmith/lib/Plugin.js:5:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`

can you please fix this.

**Comment by mixtur** [comment]
Quick fix - update nodejs. I'll fix it for older versions of nodejs later this day.

**Comment by shaurabh-singh** [comment]
Thanks  @mixtur, updating nodejs version fixed this issue.
