### ISSUE TITLE
TypeError: Cannot read property 'watchRun' of undefined

### ISSUE THREAD

**Issue by wzup** [mixtur/webpack-spritesmith#62]
I get this error thrown. Why?
```
An error was thrown while starting webpack-serve.
   Error: An error was thrown while initializing Webpack
  TypeError: Cannot read property 'watchRun' of undefined
    at getOptions.then (/home/user/app//node_modules/webpack-serve/index.js:35:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Error: An error was thrown while initializing Webpack
  TypeError: Cannot read property 'watchRun' of undefined
    at getOptions.then (/home/user/app//node_modules/webpack-serve/index.js:35:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3**
```

This error appears to be in your plugin 
https://github.com/mixtur/webpack-spritesmith/blob/8e146881c439d4df142bbcd7b7f8f9e8cc8aba2c/lib/Plugin.js#L38

I'm trying to start `webpack-serve`
```
$ node serve.config.js
```

`serve.config.js` config:
```
'use strict';

const serve = require('webpack-serve');
const wpConfig = require('./webpack.config.js');

let serverConfig = {
    hot: true,           // Instruct the client not to apply Hot Module Replacement patches
}

serve({
    options: serverConfig,
    config: wpConfig,
});
```

My webpack config:
https://gist.github.com/wzup/54d2a81c10ab8d22a66e53f22fd2e07a

**Comment by mixtur** [comment]
That is very weird. It should either be different error, or not at all.
For now you can rollback to 0.4.0. I'll look deeper into it as soon as I can.

What are your versions of node and webpack?

**Comment by wzup** [comment]
I close the issue. It waas not `webpack-spritesmith` issue. It was `webpack`'s issue.
